webtalk_init -webtalk_dir F:/MIPS_CPU/vga_controller/vga_controller/vga_controller.sim/sim_1/behav/xsim/xsim.dir/tb_vga_ToplevelShell_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 23 14:53:18 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211917670_0_0_664" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0f0fa434-6ef2-474c-89dc-5e2c3dd38136" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cd24038aade8464c93a4a0fe2491004b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "17 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14508_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3278323701 -regid "211917670_0_0_664" -xml F:/MIPS_CPU/vga_controller/vga_controller/vga_controller.sim/sim_1/behav/xsim/xsim.dir/tb_vga_ToplevelShell_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/MIPS_CPU/vga_controller/vga_controller/vga_controller.sim/sim_1/behav/xsim/xsim.dir/tb_vga_ToplevelShell_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/MIPS_CPU/vga_controller/vga_controller/vga_controller.sim/sim_1/behav/xsim/xsim.dir/tb_vga_ToplevelShell_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
