# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/MIPS_CPU/vga_controller/vga_controller/vga_controller.cache/wt [current_project]
set_property parent.project_path F:/MIPS_CPU/vga_controller/vga_controller/vga_controller.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/MIPS_CPU/vga_controller/vga_controller/vga_controller.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/MIPS_CPU/vga_controller/verilog/LogisimClockComponent.v
  F:/MIPS_CPU/vga_controller/verilog/LogisimTickGenerator.v
  F:/MIPS_CPU/vga_controller/verilog/vga_controller.v
  F:/MIPS_CPU/vga_controller/verilog/vga_counter.v
  F:/MIPS_CPU/vga_controller/verilog/vga_sync.v
  F:/MIPS_CPU/vga_controller/verilog/vga_TopLevelShell.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/MIPS_CPU/vga_controller/xdc/vga_controller.xdc
set_property used_in_implementation false [get_files F:/MIPS_CPU/vga_controller/xdc/vga_controller.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top vga_ToplevelShell -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_ToplevelShell.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_ToplevelShell_utilization_synth.rpt -pb vga_ToplevelShell_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
